// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Univers.Data.Context;

#nullable disable

namespace Univers.Data.Migrations
{
    [DbContext(typeof(UniversContext))]
    [Migration("20260210235836_CreationBD")]
    partial class CreationBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Univers.Domain.Entities.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmId"));

                    b.Property<DateOnly>("DateSortie")
                        .HasColumnType("date");

                    b.Property<int>("Duree")
                        .HasColumnType("int");

                    b.Property<byte>("Etoile")
                        .HasColumnType("tinyint");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmId");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("Univers.Domain.Entities.Franchise", b =>
                {
                    b.Property<int>("FranchiseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FranchiseId"));

                    b.Property<short>("AnneeCreation")
                        .HasColumnType("smallint");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proprietaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteWeb")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FranchiseId");

                    b.ToTable("Franchises");
                });

            modelBuilder.Entity("Univers.Domain.Entities.Personnage", b =>
                {
                    b.Property<int>("PersonnageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonnageId"));

                    b.Property<DateOnly>("DateNaissance")
                        .HasColumnType("date");

                    b.Property<bool>("EstVilain")
                        .HasColumnType("bit");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<string>("IdentiteReelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonnageId");

                    b.HasIndex("FranchiseId");

                    b.ToTable("Personnages");
                });

            modelBuilder.Entity("Univers.Domain.Entities.Personnage", b =>
                {
                    b.HasOne("Univers.Domain.Entities.Franchise", "Franchise")
                        .WithMany("PersonnageListe")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");
                });

            modelBuilder.Entity("Univers.Domain.Entities.Franchise", b =>
                {
                    b.Navigation("PersonnageListe");
                });
#pragma warning restore 612, 618
        }
    }
}
